### ISSUE TITLE
Error while convertir large byte ascii text 

### ISSUE THREAD

**Issue by pdelteil** [dadadel/binmake#3]
This is what I get:

echo "%b00000000010111110000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000" | binmake
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoull
Aborted (core dumped)

**Comment by dadadel** [comment]
Hi @pdelteil 
This is a large binary number (about 16 bytes) while the higher number type managed is 64 bits, that is 8 bytes.
So this is a misuse of binmake. If you want to represent a so big number of bytes in binary representation you might use separated bytes like : 
```
echo "binary 00000000 01011111 000000010 00000000 00000000 00000000...." | ./binmake
```
(or in the opposite order depending on endianness)

**Comment by dadadel** [comment]
Note that you didn't provide ASCII text but bits (binary digits)
